os: osx
install:
  # ==== Miniconda installation =====
  - curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh
  - sh miniconda.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Debug info
  # ==== Neuron installation ========
  - git clone https://github.com/nrnhines/nrn.git
  - cd nrn
  - export PYTHONHOME=$HOME/miniconda3
  - export NEURON_HOME=/Applications/NEURON-7.5/nrn/x86_64
  - export LD_LIBRARY_PATH=$PYTHONHOME/lib
  - export PATH=$PATH:$NEURON_HOME/bin
  - export PYTHONPATH=$PYTHONPATH:$NEURON_HOME/../lib/python/
  - sh build.sh
  - ./configure --prefix=$NEURON_HOME/.. --with-nrnpython=python3 --without-x
  - make
  - sudo make install
  - cd ..

script: 
  # To do: make python do something more interesting like download a NEURON model and run it.  
  - python -c "import neuron"
  - python script.py
