os: OSX
python:
  - "3.6"
install:
  # ==== Miniconda installation =====
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Debug info
  # ==== Neuron installation ========
  - git clone https://github.com/nrnhines/nrn.git
  - cd nrn
  - export NEURON_HOME=/Applications/NEURON-7.5
  - export LD_LIBRARY_PATH=$PYTHONHOME/lib
  - export PATH=$PATH:$NEURON_HOME/nrn/x86_64/bin
  - export PYTHONPATH=$PYTHONPATH:$NEURON_HOME/nrn/lib/python/
  - sh build.sh
  - ./configure --prefix=$NEURON_HOME/nrn --with-nrnpython=python3
  - make
  - sudo make install

script: 
  - nrniv
  - python -c "import neuron"